---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: livingdocs/varnish
    tags: [6.4.0-r3, latest]

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: livingdocs/varnish
    tags: [6.4.0-r3, latest]
  when:
    branch: [master]

trigger:
  event: [push]

---
kind: signature
hmac: b35be27c5f54a54c4334120c1eda7dfc9f464983b5089bf9f77c034f9bafed75

...
