---
kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    dry_run: true
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: livingdocs/varnish
    tags: [6.4.0-r1, latest]

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: livingdocs/varnish
    tags: [6.4.0-r1, latest]
  when:
    branch: [master]

trigger:
  event: [push]

---
kind: signature
hmac: 47c016b63a56ef4426e47367d47beec355af08991dc8ce43c9d82ce143f949eb

...
