clusters:
- name: delivery
  address: delivery:9010
- name: redirects
  address: redirects:3000
- name: externalScripts
  address: nca.xoqiya.han-solo.net:80
parameters:
  default_ttl: 600
hooks:
  vclRecvStart: |
    if (req.restarts == 0) {
        set req.http.Orig-Url = req.url;
        set req.url = "/api/probe-bmg/sao" + regsub(req.url, "/$", "");
        set req.backend_hint = redirects.backend();
        return (hash);
    }
  vclRecvEnd: |
    if (req.url ~ "^/external-scripts/") {
        set req.url = regsub(req.url, "^/external-scripts", "");
        set req.backend_hint = externalScripts.backend();
        return (hash);
    }
  vclDeliverStart: |
    if (req.restarts == 0) {
        if (resp.status == 301) {
            return (deliver);
        } else if (resp.status == 302) {
            return (deliver);
        } else if (resp.status == 410) {
            return (deliver);
        } else {
            set req.url = req.http.Orig-Url;
            set req.backend_hint = delivery.backend();
            return (restart);
        }
    }
  vclBackendFetchStart: |
    if (bereq.backend == externalScripts.backend()) {
        set bereq.http.Host = "nca.xoqiya.han-solo.net";
    }
  vclBackendResponse: |
    if (bereq.backend == externalScripts.backend()) {
        set beresp.ttl = 5m;
    }
