version: '3.8'
services:
  varnish:
    image: forwardpublishing/fp-varnish:v1.0.0
    container_name: fp-varnish
    volumes:
      - ./config.yaml:/etc/varnish/source/config.yaml:ro
    ports:
      - "8080:8080"